---

gazellacom_mode:                                #backup, copyfromprod, restore, cleandb
gazellacom_project: client                      # client
gazellacom_environment: integration             #integration, production
gazellacom_db_remote_host: 
gazellacom_db_remote_name:
gazellacom_db_remote_port: 5432
gazellacom_db_remote_username: "{{ db_username_remote }}"
gazellacom_db_remote_password: "{{ db_password_remote }}"
gazellacom_db_local_host: 
gazellacom_db_local_name:
gazellacom_db_local_port: 5432
gazellacom_db_local_username: "{{ db_username}}"
gazellacom_db_local_password: "{{ db_password }}"
gazellacom_db_local_username_main: "{{ db_username_main }}"
gazellacom_db_local_password_main: "{{ db_password_main }}"
gazellacom_local_base: '/opt/.awx/db'
gazellacom_local_workdir: "{{ gazellacom_local_base }}/{{ gazellacom_environment }}"
gazellacom_remote_workdir: "{{ gazellacom_local_base }}/remote"
gazellacom_awx_user:  awx_user
gazellacom_awx_group:  "{{ gazella_group_security }}"
gazellacom_db_restore_node: 10
gazellacom_db_local_retention: 1

gazellacom_awx_ser_passwd: "*"
gazellacom_awx_user_update_password: always
gazellacom_awx_user_shell: /bin/bash

