---
- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Add Gazellacom system group security"
  become: yes
  ansible.builtin.group:
    name: "{{ gazellacom_client_group }}"
    state: present
  tags:
    - gazellacom_user

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Add Gazellacom AWX user"
  ansible.builtin.user:
    name: "{{ gazellacom_client_user }}"
    group: "{{ gazellacom_client_group }}"
    state: present
    shell: "{{ gazellacom_client_user_shell }}"
    password: "{{ gazellacom_client_user_passwd }}"
    update_password: "{{ gazellacom_client_user_update_password }}"
    system: "{{ gazellacom_client_user_system }}"
  tags:
    - gazellacom_user

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Add directory for /home/{{ gazellacom_client_user }}/.ssh User"
  file:
    path: "/home/{{ gazellacom_client_user }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ gazellacom_client_user }}"
    group: "{{ gazellacom_client_group }}"

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Copy the file from bbuffer key folder  {{ gazellacom_client_user }}"
  ansible.builtin.copy: 
    src: "key/{{ gazellacom_project|upper }}-AWX-USER.pub"
    dest: "/home/{{ gazellacom_client_user }}/.ssh/{{ gazellacom_project|upper }}-AWX-USER.pub"

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Add key for {{ gazellacom_client_user }} User"
  ansible.posix.authorized_key:
    user: "{{ gazellacom_client_user }}"
    state: present
    key: "{{ lookup('file', 'key/{{ gazellacom_project|upper }}-AWX-USER.pub') }}"


- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Create sudoers config for {{ gazellacom_client_user }} user"
  ansible.builtin.template:
    src: gazellacom-sudo.j2
    dest: "/etc/sudoers.d/{{ gazellacom_client_user }}"
    mode: 0440
    owner: root
    group: root
    validate: "/usr/sbin/visudo -cf %s"

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} - Delete file {{ gazellacom_project|upper }}-AWX-USER.pub"
  ansible.builtin.file:
    path: "/home/{{ gazellacom_client_user }}/.ssh/{{ gazellacom_project|upper }}-AWX-USER.pub"
    state: absent
  ignore_errors: yes

- name: "SSH USER {{ gazellacom_project }} {{ gazellacom_environment }} -  Create awx  directory"
  ansible.builtin.file:
    path: "{{ gazellacom_client_base }}"
    state: directory
    owner: "{{ gazellacom_client_user }}"
    group: "{{ gazellacom_client_group }}"
    mode: 0775
    force: no
  tags:
    - gazellacom_log



